version: "3.8"

services:
  fastapi:
    build:
      context: ./src
      dockerfile: dockerfile_old
    container_name: fastapi_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network

  worker:
    build:
      context: ./src
      dockerfile: dockerfile_old
    container_name: celery_worker
    command: ["celery", "-A", "worker", "worker", "--loglevel=info"]
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network

  redis:
    image: "redis:latest"
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
