version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Tắt bảo mật
      - network.host=0.0.0.0
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS="http://es:9200"
    networks:
      - elastic
  
volumes:
  data:
    driver: local
networks:
  elastic:
    driver: bridge