version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'
    restart: unless-stopped

  kafka-01:
    image: wurstmeister/kafka
    container_name: kafka-01
    ports:
      - '9192:9092'
      - '29194:29094'
      # - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://kafka-01:29092,OUTSIDE://kafka-01:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-01:29092,OUTSIDE://34.171.201.34:9192
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "nhapho_batch:3:3,bietthu_batch:3:3,nharieng_batch:3:3,chungcu_batch:3:3,nhapho:3:3,bietthu:3:3,nharieng:3:3,chungcu:3:3,test:3:3"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ./data/kafka-01/:/tmp/kafka-logs/
    restart: unless-stopped

  kafka-02:
    image: wurstmeister/kafka
    container_name: kafka-02
    ports:
      - '9292:9092'
      - '29294:29094'
      # - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: INSIDE://kafka-02:29092,OUTSIDE://kafka-02:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-02:29092,OUTSIDE://34.171.201.34:9292
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "bds:3:3,i-batdongsan:3:3,nhadatviet:3:3"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ./data/kafka-02/:/tmp/kafka-logs/
    restart: unless-stopped

  kafka-03:
    image: wurstmeister/kafka
    container_name: kafka-03
    ports:
      - '9392:9092'
      - '29394:29094'
      # - '9093:9093'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: INSIDE://kafka-03:29092,OUTSIDE://kafka-03:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-03:29092,OUTSIDE://34.171.201.34:9392
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # KAFKA_CREATE_TOPICS: "bds:3:3,i-batdongsan:3:3,nhadatviet:3:3"
      KAFKA_LOG_RETENTION_HOURS: 24
    volumes:
      - ./data/kafka-03/:/tmp/kafka-logs/
    restart: unless-stopped